#!/bin/sh
. /lib/functions.sh
info()
{
    /usr/share/modem/modem_ctrl.sh info $1
}

sim_info()
{
    /usr/share/modem/modem_ctrl.sh sim_info $1
}

base_info()
{
    /usr/share/modem/modem_ctrl.sh base_info $1
}

network_info()
{
    /usr/share/modem/modem_ctrl.sh network_info $1
}


cell_info()
{
    /usr/share/modem/modem_ctrl.sh cell_info $1
}
case "$1" in
	list)
		echo '{ "info": {  }, "base_info": { }, "failme": {} }'
	;;
	call)
		case "$2" in
			"info")
                config_load modem
                config_foreach info modem-device
			;;
            "base_info")
                config_load modem
                config_foreach base_info modem-device
            ;;
            "sim_info")
                config_load modem
                config_foreach sim_info modem-device
            ;;
            "network_info")
                config_load modem
                config_foreach network_info modem-device
            ;;
            "cell_info")
                config_load modem
                config_foreach cell_info modem-device
            ;;
		esac
	;;
esac
