#!/bin/sh /etc/rc.common
START=99
STOP=13
USE_PROCD=1

#脚本目录
SCRIPT_DIR="/usr/share/modem"

#运行目录
MODEM_RUNDIR="/var/run/modem"
MODEM_RUN_CONFIG="${MODEM_RUNDIR}/config.cache"
#导入组件工具
source "${SCRIPT_DIR}/modem_scan.sh"

service_triggers()
{
	procd_add_reload_trigger "modem"

}

start_service() {
    mkdir -p $MODEM_RUNDIR
    
	#加载模组配置
	config_load modem
    config_foreach run_modem modem-device
}

reload_service()
{
    stop
	start
}

stop_service()
{
    #清理运行目录
    config_load modem
    config_foreach hang_modem modem-device
}



run_modem()
{
    procd_open_instance "modem_$1"
    procd_set_param command "/usr/share/modem/modem_dial.sh" "$1"
    procd_set_param respawn
    procd_close_instance
    logger -t modem_network "dial modem $1"
}

hang_modem()
{
    service_stop "modem_$1"
    "/usr/share/modem/modem_dial.sh" "$1" hang
    logger -t modem_network "hang modem $1"
}
