#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/functions.sh
start_service()
{
    config_load 'modem_ttl'
    config_get enable 'global' 'enable' '0'
    if [ "$enabled" == 0 ]; then
        return
    fi
    set_if_ttl
}

set_if_ttl()
{
    config_get ifname 'global' 'ifname'
    config_get ttl 'global' 'ttl'
    iface=$(ifstatus $ifname)
    json_load "$iface"
    json_get_var device device
    IPT="iptables"
    IPT6="ip6tables"
    logger -t modem_ttl "Setting TTL for $device to $ttl"
    $IPT -t mangle -A PREROUTING -i $device -j TTL --ttl-set $ttl
    $IPT -t mangle -A POSTROUTING -o $device -j TTL --ttl-set $ttl
    $IPT6 -t mangle -A PREROUTING -i $device -j HL --hl-set $ttl
    $IPT6 -t mangle -A POSTROUTING -o $device -j HL --hl-set $ttl
}

service_triggers()
{
	procd_add_reload_trigger "modem_ttl"
    procd_add_reload_trigger "network"
    #netdev


}

reload_service()
{
    start_service
}
